---
- hosts: all
  #remote_user: root
  #remote_user: vagrant
  remote_user: user
  become: yes
  become_method: sudo

  tasks:
  #- name: upgrade all packages
  #  package:
  #    name: "*"
  #    state: latest

  - name: Install packages ubuntu and debian
    package:
      name:
        #- cockpit
        - curl
        - wget
        - python
        - python3
        - python3-pip
        - git
        - vim
        - apt-utils
        - lvm2
      state: present
    ignore_errors: yes

  - name: add group admins for nopasswd sudo
    group:
      name: admins
      state: present


  - name: Install packages centos7 and RHEL7
    package:
      name:
        - cockpit
        #- podman
        - curl
        - wget
        - python2
        - python3
        - python3-pip
        - git
        - vim
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        #- epel-release
        #- oracle-epel-release-el8
        - sudo
        - bash-completion
        #- centos-release-scl-rh
        #- centos-release-scl
      state: present
    ignore_errors: yes


  - name: install vanilla epel 
    command: yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    when: ansible_pkg_mgr == "dnf"


  - name: sudoers file
    get_url:
      url: https://raw.githubusercontent.com/habbis/sudoers/master/admins
      dest: /etc/sudoers.d/
      mode: '0440'

  - name: Download sshd_config from git repo
    get_url:
      url: https://gitlab.com/habbis/openssh_config/raw/master/sshd_config
      dest: /etc/ssh/
      mode: '0744'

  #- name: Create group for docker
    #group:
      #name: docker
      #state: absent

  - name: add right sftp server for rhel/centos in sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '/usr/lib/openssh/sftp-server'
      line: "Subsystem  sftp /usr/libexec/openssh/sftp-server"
    #when: ansible_facts == "CentOS"
    when: ansible_pkg_mgr == "yum"


  - name: add right sftp server for rhel/centos in sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '/usr/lib/openssh/sftp-server'
      line: "Subsystem  sftp /usr/libexec/openssh/sftp-server"
    #when: ansible_facts == "CentOS"
    when: ansible_pkg_mgr == "dnf"

  - name: add user called user with sudo right
    user:
      name: user
      shell: /bin/bash
      groups: admins
      append: yes

  - name: set authorized keys from github to user
    authorized_key:
      user: user
      state: present
      key: https://github.com/habbis.keys
    ignore_errors: yes

  - name: set authorized keys from github to user
    authorized_key:
      user: root
      state: present
      key: https://github.com/habbis.keys
    ignore_errors: yes

  - name: reload sshd
    service:
      name: sshd
      state: reloaded

  - name: Add repository docker
    yum_repository:
      name: docker-ce
      description: docker-ce repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      state: present

  - name: Create group for docker
    group:
      name: docker
      state: present

  - name: add user called cusr with docke right
    user:
      name: cusr
      shell: /bin/bash
      groups: docker
      append: yes

  - name: install packages pip
    pip:
      name:
        - docker-compose
       #- podman-compose
      executable: pip3

  - name: Install Docker
    package:
      name: docker-ce
      state: present




   #- name: set authorized keys from github to virt
     #authorized_key:
       #user: virt
       #state: present
       #keys: https://github.com/habbis.keys


      #- name: enable cockpit systemd service
      #firewalld:
      #service: cockpit
      #permanent: yes
      #state: enabled
